# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:11

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

build:
    stage: build
    script:
        - apt-get update && apt-get install libpam0g-dev -y && apt-get clean
        - npm install
        - npx gulp build
    artifacts:
        paths:
            - dist

publish:
    stage: deploy
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm publish
    dependencies:
        - build
    only:
        - /^v.*$/
    except:
        - branches
    cache:
        paths:
            - node_modules/
        policy: pull
